import type { KnowledgeBaseDraft } from '@/types/knowledge-base';
import { classifyIndustry } from './industryProfiles';

// Placeholder stand-ins for real LLM calls
type EnrichableField =
  | 'companyFoundation.industry'
  | 'companyFoundation.businessModel'
  | 'positioning.companyPitch'
  | 'brandingAndStyle.writingStyle'
  | 'marketAndCustomers.targetBuyers'
  | 'marketAndCustomers.customerNeeds';

// Runs after scrapeWebsite() returns. Fills the handful of fields the real
// extractors deliberately leave null
export function enrichDraft(draft: KnowledgeBaseDraft): KnowledgeBaseDraft {
  if (draft.scrapeStatus === 'failed') return draft;

  const companyName = draft.companyName ?? 'This company';
  const offeringsText = draft.offerings
    .map((o) => `${o.name} ${o.description ?? ''}`)
    .join(' ');
  const classificationText = `${
    draft.companyFoundation.overview ?? ''
  } ${offeringsText}`;
  const profile = classifyIndustry(classificationText);

  const enrichedFieldPaths: string[] = [];
  const markEnriched = (path: EnrichableField) => enrichedFieldPaths.push(path);

  const industry = draft.companyFoundation.industry;
  const nextIndustry = industry ?? profile.industry;
  if (industry === null) markEnriched('companyFoundation.industry');

  const businessModel = draft.companyFoundation.businessModel;
  const nextBusinessModel =
    businessModel ?? profile.businessModelTemplate(companyName);
  if (businessModel === null) markEnriched('companyFoundation.businessModel');

  const companyPitch = draft.positioning.companyPitch;
  const nextCompanyPitch =
    companyPitch ?? mockCompanyPitch(draft, companyName, nextIndustry);
  if (companyPitch === null) markEnriched('positioning.companyPitch');

  const writingStyle = draft.brandingAndStyle.writingStyle;
  const nextWritingStyle =
    writingStyle ?? mockWritingStyle(draft.companyFoundation.overview);
  if (writingStyle === null) markEnriched('brandingAndStyle.writingStyle');

  const targetBuyers = draft.marketAndCustomers.targetBuyers;
  const nextTargetBuyers =
    targetBuyers.length > 0 ? targetBuyers : profile.targetBuyers;
  if (targetBuyers.length === 0)
    markEnriched('marketAndCustomers.targetBuyers');

  const customerNeeds = draft.marketAndCustomers.customerNeeds;
  const nextCustomerNeeds = customerNeeds ?? profile.customerNeeds;
  if (customerNeeds === null) markEnriched('marketAndCustomers.customerNeeds');

  const enrichedFlags = draft.dataQuality.flags.map((flag) =>
    enrichedFieldPaths.includes(flag.field) && flag.status === 'missing'
      ? {
          ...flag,
          status: 'ai_generated_mock' as const,
          note: 'Placeholder generated by mock enrichment — see /prompts.',
        }
      : flag
  );

  return {
    ...draft,
    companyFoundation: {
      ...draft.companyFoundation,
      industry: nextIndustry,
      businessModel: nextBusinessModel,
    },
    positioning: {
      ...draft.positioning,
      companyPitch: nextCompanyPitch,
    },
    brandingAndStyle: {
      ...draft.brandingAndStyle,
      writingStyle: nextWritingStyle,
    },
    marketAndCustomers: {
      ...draft.marketAndCustomers,
      targetBuyers: nextTargetBuyers,
      customerNeeds: nextCustomerNeeds,
    },
    dataQuality: { flags: enrichedFlags },
  };
}

// Mocks /prompts/company-pitch-prompt.md
function mockCompanyPitch(
  draft: KnowledgeBaseDraft,
  companyName: string,
  industry: string
): string {
  const topOfferings = draft.offerings
    .slice(0, 3)
    .map((o) => o.name)
    .filter(Boolean);

  const offeringsPhrase =
    topOfferings.length > 0
      ? `offering ${joinWithAnd(topOfferings)}`
      : 'offering services tailored to their local market';

  const article = /^[aeiou]/i.test(industry) ? 'an' : 'a';

  return (
    `${companyName} is ${article} ${industry.toLowerCase()} business, ${offeringsPhrase}. ` +
    `[Placeholder pitch generated by mock AI enrichment — a production build would ` +
    `send the scraped overview and offerings to an LLM per /prompts/company-pitch-prompt.md.]`
  );
}

// Mocks /prompts/writing-style-prompt.md
function mockWritingStyle(overview: string | null): string {
  if (!overview) {
    return (
      'Not enough scraped copy to analyze automatically. A production build ' +
      'would send the homepage text to an LLM per /prompts/writing-style-prompt.md.'
    );
  }

  const sentenceCount = overview.split(/[.!?]+/).filter(Boolean).length || 1;
  const avgWordsPerSentence = overview.split(/\s+/).length / sentenceCount;
  const lengthDescriptor =
    avgWordsPerSentence > 22
      ? 'longer, detailed sentences'
      : 'short, direct sentences';

  return (
    `Placeholder analysis based on the homepage overview: appears to favor ${lengthDescriptor}. ` +
    `[Mock AI enrichment — a production build would send the full page text to an LLM ` +
    `per /prompts/writing-style-prompt.md for a real tone/voice analysis.]`
  );
}

function joinWithAnd(items: string[]): string {
  if (items.length === 1) return items[0];
  if (items.length === 2) return `${items[0]} and ${items[1]}`;
  return `${items.slice(0, -1).join(', ')}, and ${items[items.length - 1]}`;
}
